### ISSUE TITLE
docker-codimd on rpi4

### ISSUE THREAD

**Issue by Schnegg** [linuxserver/docker-codimd#11]
Is it possible to operate the container on the Raspberry Pi 4?
When I install the container with docker-compose, the following error message appears:

codimd     | Sequelize CLI [Node: 10.17.0, CLI: 5.5.0, ORM: 5.8.12]
codimd     | 
codimd     | Loaded configuration file "../../config/config.json".
codimd     | == 20150504155329-create-users: migrating =======
codimd     | 
codimd     | ERROR: Specified key was too long; max key length is 767 bytes
codimd     | 
codimd     | 

Information about the system:
Linux rpi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Many thanks for the help.

**Comment by CHBMB** [comment]
Might be useful to include the info we ask for in the template.

```
## Current Behavior
<!--- Tell us what happens instead of the expected behavior -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

## Environment
**OS:**      
**CPU architecture:** x86_64/arm32/arm64      
**How docker service was installed:**      
<!--- Providing context helps us come up with a solution that is most useful in the real world -->

## Command used to create docker container (run/create/compose/screenshot)
<!--- Provide your docker create/run command or compose yaml snippet, or a screenshot of settings if using a gui to create the container -->

## Docker logs
<!--- Provide a full docker log, output of "docker logs codimd" -->
```

**Comment by Schnegg** [comment]
sorry

## Current Behavior
When the container codimd starts, an error message appears.

## Steps to Reproduce
1. on the rpi4 the image buster installed
2. everything updated
3. docker installed according to the following instructions: [https://dev.to/rohansawant/installing-docker-and-docker-compose-on-the-raspberry-pi-in-5-simple-steps-3mgl](url)
4. created the file docker-compose.yml and insert the docker-compose schema according to the documentation in README.md
5. the passwords and locations changed in `docker-compose.yml`
5. run `docker-compose up` command.

## Environment
Linux rpi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

## Command used to create docker container (run/create/compose/screenshot)
As described above.
On the pi also runs portainer

## Docker logs

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 10-adduser: executing... 
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \ 
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> We gratefully accept donations at:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing... 
> /var/run/s6/etc/cont-init.d/30-config: line 32: warning: command substitution: ignored null byte in input
> /var/run/s6/etc/cont-init.d/30-config: line 32: warning: command substitution: ignored null byte in input
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-scripts: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-scripts: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> 
> Sequelize CLI [Node: 10.17.0, CLI: 5.5.0, ORM: 5.8.12]
> 
> Loaded configuration file "../../config/config.json".
> == 20150504155329-create-users: migrating =======
> 
> ERROR: Specified key was too long; max key length is 767 bytes
> 
> 
> Sequelize CLI [Node: 10.17.0, CLI: 5.5.0, ORM: 5.8.12]
> 
> Loaded configuration file "../../config/config.json".
> == 20150504155329-create-users: migrating =======
> 
> ERROR: Specified key was too long; max key length is 767 bytes
>

**Comment by aptalca** [comment]
Post the compose yml you used

**Comment by Schnegg** [comment]
passwords have been changed.
my docker-compose.yml file:

```
version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: codimd_mariadb
    restart: always
    volumes:
      - /home/pi/docker-codimd/database/:/config
    environment:
      - MYSQL_ROOT_PASSWORD=mTVmBvcpKGAa
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=rilow87abene
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  codimd:
    image: linuxserver/codimd:latest
    container_name: codimd
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /home/pi/docker-codimd/codimddata/:/config
    environment:
      - DB_HOST=mariadb
      - DB_USER=codimd
      - DB_PASS=rilow87abene
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"

```

**Comment by aptalca** [comment]
This is exactly why we ask you to post all the info in the template and do not accept answers like "I followed such directions or I used the example".

You changed the container name for mariadb to codimd_mariadb but set the db_host var to mariadb. That's why codimd cannot connect to it. Make sure they match.

**Comment by Schnegg** [comment]
Thank you.
Except for the passwords, I have not changed anything. Maybe it is wrong in the documentation?
Now I have adapted the file according to your recommendations. It still does not work.

```
version: "3"
services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: codimd_mariadb
    restart: always
    volumes:
      - /home/pi/docker-codimd/database/:/config
    environment:
      - MYSQL_ROOT_PASSWORD=mTVmBvcpKGAa
      - MYSQL_DATABASE=codimd
      - MYSQL_USER=codimd
      - MYSQL_PASSWORD=rilow87abene
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  codimd:
    image: linuxserver/codimd:latest
    container_name: codimd
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /home/pi/docker-codimd/codimddata/:/config
    environment:
      - DB_HOST=codimd_mariadb
      - DB_USER=codimd
      - DB_PASS=rilow87abene
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - "3000:3000"
```
