### ISSUE TITLE
Error 500 on almost every page

### ISSUE THREAD

**Issue by AlexKalopsia** [linuxserver/docker-codimd#13]
I just started using CodiMD and I have one issue, where all of the Intro page links lead to 500 error. It's the same if I open my profile and click on Features. I am wondering if this is just a normal result of self-hosting, in which case it would still be nice to make sure those link keep pointing at the CodiMD website rather than the selfhosted address.

Broken Links:
- Real time collaboration
- Works with charts and MathJax
- Supports slide mode
- Releases (footer)
- Profile -> Features

## Expected Behavior
These links should not be changed with the local ip but lead to the official CodiMD website

## Current Behavior
The links point to myip/xxxxx resulting in not finding any of those pages

## Environment
Running with docker-compose on Synology NAS

## Command used to create docker container (run/create/compose/screenshot)
```
  codimd:
    container_name: codimd
    image: linuxserver/codimd:latest
    volumes:
      - /volume1/docker/codimd/config:/config
    environment:
      - DB_HOST=myip
      - DB_USER=codimd
      - DB_PASS=psw
      - DB_NAME=db
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Stockholm
    ports:
      - 3001:3000
    depends_on:
      - mariadb
    restart: unless-stopped
```
