### ISSUE TITLE
Can't login after latest update

### ISSUE THREAD

**Issue by AlexKalopsia** [linuxserver/docker-codimd#14]
## Expected Behavior
I should be able to sign in and access my notes

## Current Behavior
I just updated my image and now I can reach the landing page, but clicking on Login nothing happens (seems like there's not even a link working). I can open a guest note, but to the right it says OFFLINE and I can't edit anything. 

## Steps to Reproduce
* docker-compose pull codimd
* docker stop codimd
* docker rm codimd
* docker-compose up -d --no-deps codimd

## Environment
**OS: Synology NAS + Docker**      
**CPU architecture:** x86_64      
**How docker service was installed:**      

## Command used to create docker container (run/create/compose/screenshot)
```
codimd:
    container_name: codimd
    image: linuxserver/codimd:latest
    volumes:
      - /volume1/docker/codimd/config:/config
    environment:
      - DB_HOST=${IP}
      - DB_NAME=${CODIMD_DB}
      - DB_USER=${CODIMD_USER}
      - DB_PASS=${CODIMD_PSW}
      - DB_PORT=3306
      - PGID=1027
      - PUID=100
      - TZ=${TZ}
    ports:
      - 3001:3000
    depends_on:
      - mariadb
    restart: unless-stopped
```

## Docker logs
https://pastebin.com/dRMEP4sB
